name: Production Deployment

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: echo "deploy production! ${{ github.ref }}"
