name: Production Deployment

on:
  workflow_dispatch:

jobs:

  deploy-production:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3


  publish-release:
    needs: [deploy-production]
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    outputs:
      new_tag: ${{ steps.publish-release.outputs.tag_name }}
      
    steps:
      - uses: release-drafter/release-drafter@v5.19.0
        id: publish-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish: true

  tag-sentry:
    needs: [publish-release]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: echo "deploy production! ${{ needs.publish-release.outputs.new_tag }}"
