name: Production Deployment

on:
  workflow_dispatch:

jobs:

  deploy-production:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  bump-version:
    needs: [deploy-production]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    outputs:
      new_tag: ${{ steps.bump-version.outputs.new_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        id: bump-version
        with:
          github_token: ${{ secrets.GH_ACTION_PA_TOKEN }}

  tag-sentry:
    needs: [bump-version]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: echo "deploy production! ${{ needs.bump-version.outputs.new_tag }}"
