name: 'Release'
on:
  push:
    tags:
      - '*'


jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration: ".github/changelog-builder-configuration.json"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
        env:
          token: ${{ secrets.GITHUB_TOKEN }}