name: Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:

  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: release-drafter/release-drafter@v5.19.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish: true
