name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v6.0
      id: bump_version_push_tag
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.bump_version_push_tag.outputs.new_tag }}
